name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build_and_test:
    env:
      BUILD_CONFIG: "Release"
      HEADLESS: "true"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Setup Reqnroll
        run: dotnet new install Reqnroll.Templates.DotNet

      - name: Install Chrome for Selenium
        uses: browser-actions/setup-chrome@v1

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests and Generate Coverage
        id: test
        continue-on-error: true
        run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --results-directory "./TestResults"
        
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: false

      - name: Add XML report to job summary
        shell: bash
        run: |
          echo '### XML Report Content' >> $GITHUB_STEP_SUMMARY
          echo '```xml' >> $GITHUB_STEP_SUMMARY
          # Find the real coverage file
          COV_FILE=$(find TestResults -name "coverage.cobertura.xml" | head -n 1)
          cat "$COV_FILE" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

